project_id = "ulomnesokzzflfslgrbf"

[functions.suggest-meeting-times]
verify_jwt = false

[functions.standardize-interest]
verify_jwt = false

[functions.generate-interest-suggestions]
verify_jwt = false

[functions.parse-availability]
verify_jwt = false

[functions.generate-user-story]
verify_jwt = false
